### ISSUE TITLE
Hard coded memberof attribute in LdapHelper

### ISSUE THREAD

**Issue by istvano** [innoq/LiQID#6]
Hi Guys,

I have found a hard-coded refrerence causing users not loaded in LdapHelper

    /**
     * Load all Groups for a given User.
     *
     * @param user the given User.
     * @return Groups as a Set of Nodes for that User.
     */
    public Set<Node> getGroupsForUser(Node user) {
        Set<Node> groups = new TreeSet<Node>();
        try {
            String query = "(& (objectClass=" + groupObjectClass + ") (" + groupMemberAttribut + "=" + ((LdapUser) user).getDn() + "))";

in this method you use groupMemberAttribut  to build the ldapsearch 

Although in this method. It is HARD-CODED to memberOf !

    /**
     * Load all Users for a given Group.
     *
     * @param group the given Group.
     * @return Users as a Set of Nodes for that Group.
     */
    public Set<Node> getUsersForGroup(Node group) {
        Set<Node> users = new TreeSet<Node>();
        try {
            // TODO we need to find some solution for memberOf overlay.
            String query = "(&(objectClass=" + userObjectClass + ") (memberOf=" + ((LdapGroup) group).getDn() + "))";

this causing the getUsersForGroup not loading any users if the group attribute is anything different from memberOf

I think it is a very easy fix

**Comment by phaus** [comment]
fixed with https://github.com/innoq/LiQID/commit/1c01d75dfd6095437275f138f15efc85b87a7d64
